apiVersion: v1
kind: Pod
metadata:
  name: hadoop-single-node
  labels:
    run: hadoop-single-node
spec:
  hostname: hadoop-single-node
  containers:
  - name: hadoop
    image: croken98/hadoop_local
    securityContext:
      privileged: true
    command: [ "/bin/bash", "-c", "--" ]       
    args: [ "while true; do sleep 2073600; done;" ]
    volumeMounts:
    - name: external-data
      mountPath: /external
  volumes:
  - name: external-data
    hostPath:
      path: /mnt/d/bigdata/
      type: Directory
      type: DirectoryOrCreate